config/routes.rb
Rails.application.routes.draw do

  # root route if signed in
  authenticated do
    root 'welcome#index', as: :authenticated_root
  end

  # default root route
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  # rename paths
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  resources :courses do
    resources :cohorts
  end

  resources :instructors do
    resources :users
  end

  resources :admins do
    resources :users
  end

  resources :students

  resources :grades

end

app/models/admin.rb
class Admin < ApplicationRecord
  has_one :user, as: :userable, dependent: :destroy
  accepts_nested_attributes_for :user, allow_destroy: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  belongs_to :course
  belongs_to :instructor
  has_many :grades, dependent: :destroy
  has_many :students, through: :grades

  default_scope { order(:id) }
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts, dependent: :destroy
  accepts_nested_attributes_for :cohorts, allow_destroy: true

  default_scope { order(:id) }
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
  belongs_to :cohort
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :cohorts
  has_one :user, as: :userable, dependent: :destroy
  accepts_nested_attributes_for :user, allow_destroy: true

  default_scope { order(:id) }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :grades, dependent: :destroy
  has_many :cohorts, through: :grades

  default_scope { order(:id) }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :userable, polymorphic: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  def index
    @admins = Admin.all
  end

  def show
    @admin
  end

  def new
    @admin = Admin.new
    @admin.build_user
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      flash[:success] = "Admin '#{@admin.full_name}' created successfully."
      respond_to { |format|
        format.html { redirect_to admins_path }
        format.js
      }
    end
  end

  def edit
    @admin
  end

  def update
    if @admin.update(admin_params)
      flash[:alert] = "Admin '#{@admin.full_name}' updated successfully."
    end
  end

  def destroy
    @admin.destroy
    flash[:error] = "Admin '#{@admin.full_name}' destroyed successfully."
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(
      :first_name, :last_name, :age, :degree,
      user_attributes: [:email, :password]
    )
  end
end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController

  before_action :set_course, only: [:index, :show, :new, :edit]
  before_action :set_cohort, only: [:show, :edit, :update, :destroy]
  before_action :set_instructors, only: [:new, :edit]

  # links to /courses/:course_id/cohorts route
  def index
    @course
    @cohorts = Cohort.where(course_id: params[:course_id])
  end

  # links to courses/:course_id/cohorts/:id route
  def show
    @cohort
    @course
    @grade = Grade.new
    @students = @cohort.students
    @students_not_in_cohort = Student.joins('LEFT OUTER JOIN grades ON grades.student_id = students.id').where.not(id: Grade.where(cohort_id: @cohort.id).pluck(:student_id)).distinct
    @instructor = @cohort.instructor
  end

  def new
    @course
    @cohort = Cohort.new
    @instructors
  end

  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.save
      flash[:success] = "Cohort '#{@cohort.name}' created successfully."
      respond_to { |format|
        format.html { redirect_to course_cohorts_path(params[:course_id]) }
        format.js
      }
    end
  end

  def edit
    @cohort
    @course
    @instructors
  end

  def update
    if @cohort.update(cohort_params)
      flash[:alert] = "Cohort '#{@cohort.name}' updated successfully."
      # redirect_to course_cohorts_path(params[:course_id])
    end
  end

  def destroy
    @cohort.destroy
    flash[:error] = "Cohort '#{@cohort.name}' destroyed successfully."
    # redirect_to course_cohorts_path(params[:course_id])
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def set_cohort
    @cohort = Cohort.find(params[:id])
  end

  def set_instructors
    @instructors = Instructor.all
  end

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date, :instructor_id, :course_id)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  before_action :set_course, only: [:edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:success] = "Course '#{@course.name}' created successfully."
      respond_to { |format|
        format.html { redirect_to courses_path }
        format.js
      }
    end
  end

  def edit
    @course
  end

  def update
    if @course.update(course_params)
      flash[:alert] = "Course '#{@course.name}' updated successfully."
    end
  end

  def destroy
    @course.destroy
    flash[:error] = "Course '#{@course.name}' destroyed successfully."
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:name, :hours)
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

  before_action :set_grade, only: [:edit, :update, :destroy]

  def index
  end

  def new
  end

  def create
    @grade = Grade.new(grade_params)
    if @grade.save
      flash[:success] = "Student '#{@grade.student.full_name}' successfully added to cohort."
      # redirect_to course_cohort_path(@grade.cohort.course, @grade.cohort)
    end
  end

  def edit
    @grade
  end

  def update
    if @grade.update(grade_params)
      flash[:alert] = "Grade for '#{@grade.student.full_name}' updated successfully."
      # redirect_to course_cohort_path(@grade.cohort.course, @grade.cohort)
    end
  end

  def destroy
    @grade.destroy
    flash[:error] = "Student '#{@grade.student.full_name}' removed from cohort successfully."
  end

  private

  def set_grade
    @grade = Grade.find(params[:id])
  end

  def grade_params
    params.require(:grade).permit(:cohort_id, :student_id, :pass)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @course_count = Course.count
    @cohort_count = Cohort.count
    @student_count = Student.count
    @instructor_count = Instructor.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end

end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/_admin.html.erb
<tr id="admin_<%= admin.id %>">
  <td><%= admin.id %></td>
  <td><%= admin.first_name %></td>
  <td><%= admin.last_name %></td>
  <td><%= admin.user.email %></td>
  <% if user_signed_in? && current_user.userable_type == "Admin" %>
    <td><%= link_to("Edit", edit_admin_path(admin), remote: true, data: { toggle: "modal", target: "#editAdminModal" }, class: 'btn btn-outline-warning btn-sm') %></td>
    <td><%= link_to "Delete", admin_path(admin), remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %></td>
  <% end %>
</tr>

app/views/admins/_form.html.erb
<%= bootstrap_form_for admin, remote: true, authenticity_token: true, data: { type: :script } do |f| %>
    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.fields_for :user do |p| %>
      <%= p.text_field :email %>
      <%= p.password_field :password %>
    <% end %>
    <%= f.submit "Submit", class: "btn btn-outline-secondary" %>
<% end %>

app/views/admins/create.js.erb
// add element we just created to the DOM
document.getElementById("all_admins").insertAdjacentHTML("beforeend", "<%= j render partial: "admin", locals: { admin: @admin } %>");
// manually toggle modal
$("#addAdminModal").modal('toggle');
// display flash messages
$("#flash_messages").html("<%= j (render partial: 'shared/flash' , locals: { flash: flash }).html_safe %>");
// reset form
document.getElementById("new_admin").reset();
// scroll to top
$(document).ready(function () { $('html, body').animate({scrollTop:0}, 100); });

app/views/admins/destroy.js.erb
row = document.getElementById("admin_<%= @admin.id %>");
row.remove();
$("#flash_messages").html("<%= j (render partial: 'shared/flash' , locals: { flash: flash }).html_safe %>");
$(document).ready(function () { $('html, body').animate({scrollTop:0}, 100); });

app/views/admins/edit.js.erb
// if edit form already exists, replace with edit form span
if (document.getElementById("edit-form") === null) {
  document.getElementById("edit-modal-holder").innerHTML = "<span id='edit-form'></span>";
}
// replace edit form span with form partial
modal = document.getElementById("edit-form")
modal.outerHTML = "<%= j render partial: "form", locals: { admin: @admin } %>";

app/views/admins/index.html.erb
<% @page_title = "Admins" %>

<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
    <li class="breadcrumb-item active"><%= @page_title %></li>
  </ol>
  <div class="row">
    <div class="col-12">

      <!-- add button and page title -->
      <%= render partial: "shared/table_heading", locals: { body: 'Add New Admin', url: new_admin_path, modalname: "#addAdminModal" } %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th></th>
            <% if user_signed_in? && current_user.userable_type == "Admin" %>
              <th></th>
              <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody id="all_admins">
          <% @admins.each do |admin| %>
            <%= render admin %>
          <% end %>
        </tbody>
      </table>

      <div class="modal fade" id="addAdminModal" tabindex="-1" role="dialog" aria-labelledby="addAdminModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Add Admin</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span id='add-form'></span>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="editAdminModal" tabindex="-1" role="dialog" aria-labelledby="editAdminModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Edit Admin</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div id="edit-modal-holder" class="modal-body">
              <span id='edit-form'></span>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/admins/new.js.erb
modal = document.getElementById("add-form");
if (modal !== null) {
  modal.outerHTML = "<%= j render partial: "form", locals: { admin: @admin } %>"
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Admin panel for a magical bootcamp">
  <meta name="author" content="Kay Mok">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag %>
  <title>Admin Panel: <%= @page_title || "Dashboard" %></title>
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="<%= root_path %>">Admin Panel</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="<%= root_path %>">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Courses">
          <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#Courses" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-university"></i>
            <span class="nav-link-text">Courses</span>
          </a>
          <ul class="sidenav-second-level collapse" id="Courses">
            <% @courses.each do |course| %>
              <li>
                <%- # Display without toggler icon if course hsa no cohorts and current user isn't admin -%>
              <% if course.cohorts.empty? && user_signed_in? && current_user.userable_type != "Admin" %>
                <a class="nav-link"><%= course.name %></a>
              <% else %>
                <%- # Display cohorts associated with each course -%>
                <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#course<%= course.id %>"><%= course.name %></a>
                <ul class="sidenav-third-level collapse" id="course<%= course.id %>">
                  <% course.cohorts.each do |cohort| %>
                    <li>
                      <a href="<%= course_cohort_path(cohort.course, cohort) %>"><%= cohort.name %></a>
                    </li>
                  <% end %>
                  <%- # Show link to add cohort only if user is admin -%>
                  <% if user_signed_in? && current_user.userable_type == "Admin" %>
                    <li>
                      <a href="<%= new_course_cohort_path(course) %>">Add Cohort</a>
                    </li>
                  <% end %>
                </ul>
              </li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Instructors">
          <a class="nav-link" href="<%= instructors_path %>">
            <i class="fa fa-fw fa-user-circle"></i>
            <span class="nav-link-text">Instructors</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Students">
          <a class="nav-link" href="<%= students_path %>">
            <i class="fa fa-fw fa-users"></i>
            <span class="nav-link-text">Students</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Admins">
          <a class="nav-link" href="<%= admins_path %>">
            <i class="fa fa-fw fa-github-alt"></i>
            <span class="nav-link-text">Admins</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item" id="identifyCurrentUser">
          Looking good, <%= @logged_in.first_name %>.
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-envelope"></i>
            <span class="d-lg-none">Messages
              <span class="badge badge-pill badge-primary">12 New</span>
            </span>
            <span class="indicator text-primary d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="messagesDropdown">
            <h6 class="dropdown-header">New Messages:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>David Miller</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>Jane Smith</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <strong>John Doe</strong>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">View all messages</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-fw fa-bell"></i>
            <span class="d-lg-none">Alerts
              <span class="badge badge-pill badge-warning">6 New</span>
            </span>
            <span class="indicator text-warning d-none d-lg-block">
              <i class="fa fa-fw fa-circle"></i>
            </span>
          </a>
          <div class="dropdown-menu" aria-labelledby="alertsDropdown">
            <h6 class="dropdown-header">New Alerts:</h6>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-danger">
                <strong>
                  <i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">
              <span class="text-success">
                <strong>
                  <i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>
              </span>
              <span class="small float-right text-muted">11:21 AM</span>
              <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item small" href="#">View all alerts</a>
          </div>
        </li>
        <li class="nav-item">
          <form class="form-inline my-2 my-lg-0 mr-lg-2">
            <div class="input-group">
              <input class="form-control" type="text" placeholder="Search for...">
              <span class="input-group-append">
                <button class="btn btn-light" type="button">
                  <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
          </form>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
              <i class="fa fa-fw fa-sign-out"></i>Logout</a>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to fa_icon('sign-in', text: "Login"), new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="content-wrapper">
    <!-- flash messages -->
    <div class="container-fluid">
      <div id="flash_messages">
        <%= render "shared/flash" %>
      </div>
    </div>
    <%= yield %>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Admin Panel 2018</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-outline-secondary" type="button" data-dismiss="modal">Cancel</button>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Admin panel for a magical bootcamp">
  <meta name="author" content="Kay Mok">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag %>
  <title>Admin Panel: <%= @page_title || "Login" %></title>
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="<%= root_path %>">Admin Panel</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
          <a class="nav-link" href="<%= root_path %>">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Courses">
          <a class="nav-link" href="<%= courses_path %>">
            <i class="fa fa-fw fa-university"></i>
            <span class="nav-link-text">Courses</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Instructors">
          <a class="nav-link" href="<%= instructors_path %>">
            <i class="fa fa-fw fa-user-circle"></i>
            <span class="nav-link-text">Instructors</span>
          </a>
        </li>
        <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Students">
          <a class="nav-link" href="<%= students_path %>">
            <i class="fa fa-fw fa-users"></i>
            <span class="nav-link-text">Students</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav sidenav-toggler">
        <li class="nav-item">
          <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
              <i class="fa fa-fw fa-sign-out"></i>Logout</a>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to fa_icon('sign-in', text: "Login"), new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="content-wrapper">
    <!-- flash messages -->
    <div class="container-fluid">
      <div id="flash_messages">
        <%= render "shared/flash" %>
      </div>
    </div>

    <div class="container-fluid">
      <%= yield %>
    </div>

    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Admin Panel 2018</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-primary") %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

app/views/shared/_flash.html.erb
<% if !flash.blank? %>
  <% flash.each do |type, message| %>
    <div class="<%= flash_class(type) %>">
      <%= message %>
    </div>
  <% end %>
  <% flash.clear %>
<% end %>