config/routes.rb
Rails.application.routes.draw do

  # root route if signed in
  authenticated do
    root 'welcome#index', as: :authenticated_root
  end

  # default root route
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  # rename paths
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  resources :courses do
    resources :cohorts
  end

  resources :instructors do
    resources :users
  end

  resources :admins do
    resources :users
  end

  resources :students

  resources :grades

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :grades, dependent: :destroy
  has_many :cohorts, through: :grades

  default_scope { order(:id) }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
    @student
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # POST /students
  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "Student '#{@student.full_name}' created successfully."
      respond_to { |format|
        format.html { redirect_to students_path }
        format.js
      }
    end
  end

  # GET /students/:id/edit
  def edit
    @student
  end

  # POST /students/:id
  def update
    if @student.update(student_params)
      flash[:alert] = "Student '#{@student.full_name}' updated successfully."
    end
  end

  # POST /students/:id (delete method)
  def destroy
    @student.destroy
    flash[:error] = "Student '#{@student.full_name}' destroyed successfully."
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:first_name, :last_name, :age, :degree)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_edit_form.html.erb
<%= bootstrap_form_for @student, remote: true, authenticity_token: true do |f| %>
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.number_field :age, max: 149 %>
  <%= f.select :degree, ['HS', 'College', 'Masters', 'PhD'] %>
  <%= f.submit "Update", class: "btn btn-outline-warning" %>
<% end %>

app/views/students/_form.html.erb
<%= bootstrap_form_for student, remote: true, authenticity_token: true, data: { type: :script } do |f| %>
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.number_field :age, max: 149 %>
  <%= f.select :degree, ['HS', 'College', 'Masters', 'PhD'] %>
  <%= f.submit "Submit", class: "btn btn-outline-secondary" %>
<% end %>

app/views/students/_student.html.erb
<tr id="student_<%= student.id %>">
  <td><%= student.id %></td>
  <td><%= student.first_name %></td>
  <td><%= student.last_name %></td>
  <td><%= student.age %></td>
  <td><%= student.degree %></td>
  <td><%= link_to("Details", student_path(student), class: "btn btn-outline-primary btn-sm") %></td>
  <% if user_signed_in? && current_user.userable_type == "Admin" %>
    <td><%= link_to("Edit", edit_student_path(student), remote: true, data: { toggle: "modal", target: "#editStudentModal" }, class: "btn btn-outline-warning btn-sm") %></td>
    <td><%= link_to "Delete", student_path(student), remote: true, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %></td>
  <% end %>
</tr>

app/views/students/create.js.erb
// add element we just created to the DOM
document.getElementById("all_students").insertAdjacentHTML("beforeend", "<%= j render partial: "student", locals: { student: @student } %>");
// manually toggle modal
$("#addStudentModal").modal('toggle');
// display flash messages
$("#flash_messages").html("<%= j (render partial: 'shared/flash' , locals: { flash: flash }).html_safe %>");
// reset form
document.getElementById("new_student").reset();
// scroll to top
$(document).ready(function () { $('html, body').animate({scrollTop:0}, 100); });

app/views/students/destroy.js.erb
row = document.getElementById("student_<%= @student.id %>");
row.remove();
$("#flash_messages").html("<%= j (render partial: 'shared/flash' , locals: { flash: flash }).html_safe %>");
$(document).ready(function () { $('html, body').animate({scrollTop:0}, 100); });

app/views/students/edit.js.erb
// if edit form already exists, replace with edit form span
if (document.getElementById("edit-form") === null) {
  document.getElementById("edit-modal-holder").innerHTML = "<span id='edit-form'></span>";
}
// replace edit form span with form partial
modal = document.getElementById("edit-form")
modal.outerHTML = "<%= j render partial: "form", locals: { student: @student } %>";

app/views/students/index.html.erb
<% @page_title = "Students" %>

<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
    <li class="breadcrumb-item active"><%= @page_title %></li>
  </ol>
  <div class="row">
    <div class="col-12">

      <!-- add button and page title -->
      <%= render partial: "shared/table_heading", locals: { body: "Add New Student", url: new_student_path, modalname: "#addStudentModal" } %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Degree</th>
            <th></th>
          <% if user_signed_in? && current_user.userable_type == "Admin" %>
            <th></th>
            <th></th>
          <% end %>
          </tr>
        </thead>
        <tbody id="all_students">
          <% @students.each do |student| %>
            <%= render student %>
          <% end %>
        </tbody>
      </table>

      <div class="modal fade" id="addStudentModal" tabindex="-1" role="dialog" aria-labelledby="addStudentModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Add Student</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span id='add-form'></span>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="editStudentModal" tabindex="-1" role="dialog" aria-labelledby="editStudentModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Edit Student</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div id="edit-modal-holder" class="modal-body">
              <span id='edit-form'></span>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/students/new.html.erb
<% @page_title = "Add Student" %>

<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="<%= students_path %>">Students</a></li>
    <li class="breadcrumb-item active"><%= @page_title %></li>
  </ol>
  <div class="row justify-content-center">
    <div class="col-xl-4 col-sm-6 mb-4">
      <%= bootstrap_form_for @student do |f| %>
      <%= f.text_field :first_name %>
      <%= f.text_field :last_name %>
      <%= f.number_field :age, max: 149 %>
      <%= f.select :degree, ['HS', 'College', 'Masters', 'PhD'] %>
          <%= f.submit "Add Student", class: "btn btn-outline-success" %>
      <% end %>

    </div>
  </div>
</div>

app/views/students/new.js.erb
modal = document.getElementById("add-form");
if (modal !== null) {
  modal.outerHTML = "<%= j render partial: "form", locals: { student: @student } %>"
}

app/views/students/show.html.erb
<% @page_title = "#{@student.full_name}" %>

<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="<%= students_path %>">Students</a></li>
    <li class="breadcrumb-item active"><%= @page_title %></li>
  </ol>
  <div class="row">
    <div class="col-12">
      <br>
      <h5>Report Card</h5>
      <% if @student.cohorts.any? %>
        <table class="table table-hover mt-3">
          <thead>
            <tr>
              <th>Cohort</th>
              <th>Instructor</th>
              <th>Duration</th>
              <th>Grade</th>
            </tr>
          </thead>
          <tbody id="all_students">
            <% @student.cohorts.each do |cohort| %>
            <tr>
              <td><%= link_to("#{cohort.name}", course_cohort_path(cohort.course, cohort)) %></td>
              <td><%= link_to("#{cohort.instructor.full_name}", instructor_path(cohort.instructor)) %></td>
              <td><%= cohort.start_date.strftime("%b %d, %Y") %> - <%= cohort.end_date.strftime("%b %d, %Y") %></td>
              <td>
                <% if cohort.grades.find_by(student_id: @student.id).pass == true %>
                  Pass
                <% elsif cohort.grades.find_by(student_id: @student.id).pass == false %>
                  Fail
                <% else %>
                  N/A
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <li>Not currently enrolled in any cohorts</li>
      <% end %>
    </div>
  </div>
</div>

app/views/students/update.js.erb
// manually toggle modal
$("#editStudentModal").modal('toggle');
// re-render edited element
studentrow = document.getElementById("student_<%= @student.id %>");
studentrow.outerHTML = "<%= j render partial: "student", locals: { student: @student } %>";
// display flash messages
$("#flash_messages").html("<%= j (render partial: 'shared/flash' , locals: { flash: flash }).html_safe %>");
// turn form partial back into span
$("#edit_student_<%= @student.id %>").replaceWith("<span id='edit-form'></span>");
// scroll to top
$(document).ready(function () { $('html, body').animate({scrollTop:0}, 100); });