config/routes.rb
Rails.application.routes.draw do

  # root route if signed in
  authenticated do
    root 'welcome#index', as: :authenticated_root
  end

  # default root route
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  # rename paths
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  resources :courses do
    resources :cohorts
  end

  resources :instructors do
    resources :users
  end

  resources :admins do
    resources :users
  end

  resources :students

  resources :grades

end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :cohorts
  has_one :user, as: :userable, dependent: :destroy
  accepts_nested_attributes_for :user, allow_destroy: true

  default_scope { order(:id) }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  def index
    @instructors = Instructor.all
  end

  def show
    @instructor
  end

  def new
    @instructor = Instructor.new
    @instructor.build_user
  end

  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      flash[:success] = "Instructor '#{@instructor.full_name}' created successfully."
      respond_to { |format|
        format.html { redirect_to instructors_path }
        format.js
      }
    end
  end

  def edit
    @instructor
  end

  def update
    if @instructor.update(instructor_params)
      flash[:alert] = "Instructor '#{@instructor.full_name}' updated successfully."
    end
  end

  def destroy
    @instructor.destroy
    flash[:error] = "Instructor '#{@instructor.full_name}' destroyed successfully."
  end

  private

  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  def instructor_params
    params.require(:instructor).permit(
      :first_name, :last_name, :age, :salary, :degree,
      user_attributes: [:email, :password]
    )
  end

end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= bootstrap_form_for instructor, remote: true, authenticity_token: true, data: { type: :script } do |f| %>
    <%= f.text_field :first_name %>
    <%= f.text_field :last_name %>
    <%= f.number_field :age, max: 149 %>
    <%= f.number_field :salary, min: 1 %>
    <%= f.select :degree, ['HS', 'College', 'Masters', 'PhD'] %>
    <%= f.fields_for :user do |p| %>
      <%= p.text_field :email %>
      <%= p.password_field :password %>
    <% end %>
    <%= f.submit "Submit", class: "btn btn-outline-secondary" %>
<% end %>

app/views/instructors/_instructor.html.erb
<tr id="instructor_<%= instructor.id %>">
  <td><%= instructor.id %></td>
  <td><%= instructor.first_name %></td>
  <td><%= instructor.last_name %></td>
  <% if user_signed_in? && current_user.userable_type == "Admin" %>
    <td><%= instructor.age %></td>
    <td><%= instructor.salary %></td>
  <% end %>
  <td><%= instructor.degree %></td>
  <td><%= instructor.user.email %></td>
  <td><%= link_to("Details", instructor_path(instructor), class: 'btn btn-outline-primary btn-sm') %></td>
  <% if user_signed_in? && current_user.userable_type == "Admin" %>
    <td><%= link_to "Edit", edit_instructor_path(instructor), remote: true, data: { toggle: "modal", target: "#editInstructorModal" }, class: 'btn btn-outline-warning btn-sm' %></td>
    <td><%= link_to "Delete", instructor_path(instructor), remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %></td>
  <% end %>
</tr>

app/views/instructors/create.js.erb
// add element we just created to the DOM
document.getElementById("all_instructors").insertAdjacentHTML("beforeend", "<%= j render partial: "instructor", locals: { instructor: @instructor } %>");
// manually toggle modal
$("#addInstructorModal").modal('toggle');
// display flash messages
$("#flash_messages").html("<%= j (render partial: 'shared/flash' , locals: { flash: flash }).html_safe %>");
// reset form
document.getElementById("new_instructor").reset();
// scroll to top
$(document).ready(function () { $('html, body').animate({scrollTop:0}, 100); });

app/views/instructors/destroy.js.erb
instructorrow = document.getElementById("instructor_<%= @instructor.id %>");
instructorrow.remove();
$("#flash_messages").html("<%= j (render partial: 'shared/flash' , locals: { flash: flash }).html_safe %>");
$(document).ready(function () { $('html, body').animate({scrollTop:0}, 100); });

app/views/instructors/edit.js.erb
// if edit form already exists, replace with edit form span
if (document.getElementById("edit-form") === null) {
  document.getElementById("edit-modal-holder").innerHTML = "<span id='edit-form'></span>";
}
// replace edit form span with form partial
modal = document.getElementById("edit-form")
modal.outerHTML = "<%= j render partial: "form", locals: { instructor: @instructor } %>";

app/views/instructors/index.html.erb
<% @page_title = "Instructors" %>

<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
    <li class="breadcrumb-item active"><%= @page_title %></li>
  </ol>
  <div class="row">
    <div class="col-12">

    <!-- add button and page title -->
    <%= render partial: "shared/table_heading", locals: { body: 'Add New Instructor', url: new_instructor_path, modalname: "#addInstructorModal" } %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <% if user_signed_in? && current_user.userable_type == "Admin" %>
              <th>Age</th>
              <th>Salary</th>
            <% end %>
            <th>Degree</th>
            <th>Email</th>
            <th></th>
            <% if user_signed_in? && current_user.userable_type == "Admin" %>
              <th></th>
              <th></th>
            <% end %>
          </tr>
        </thead>
        <tbody id="all_instructors">
          <% @instructors.each do |instructor| %>
            <%= render instructor %>
          <% end %>
        </tbody>
      </table>

      <div class="modal fade" id="addInstructorModal" tabindex="-1" role="dialog" aria-labelledby="addInstructorModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div id="modal_flash_messages">
              <%= render "shared/flash" %>
            </div>
            <div class="modal-header">
              <h5 class="modal-title">Add Instructor</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span id='add-form'></span>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="editInstructorModal" tabindex="-1" role="dialog" aria-labelledby="editInstructorModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Edit Instructor</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div id="edit-modal-holder" class="modal-body">
              <span id='edit-form'></span>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/instructors/new.html.erb
<% @page_title = "Add Instructor" %>

<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="<%= instructors_path %>">Instructors</a></li>
    <li class="breadcrumb-item active"><%= @page_title %></li>
  </ol>
  <div class="row justify-content-center">
    <div class="col-xl-4 col-sm-6 mb-4">
        <%= bootstrap_form_for @instructor do |f| %>
        <%= f.text_field :first_name %>
        <%= f.text_field :last_name %>
        <%= f.number_field :age, max: 149 %>
        <%= f.number_field :salary, min: 1 %>
        <%= f.select :degree, ['HS', 'College', 'Masters', 'PhD'] %>
        <%= f.fields_for :user do |p| %>
          <%= p.text_field :email %>
          <%= p.password_field :password %>
        <% end %>
        <%= f.submit "Add Instructor", class: "btn btn-outline-success" %>
      <% end %>

    </div>
  </div>
</div>

app/views/instructors/new.js.erb
modal = document.getElementById("add-form");
if (modal !== null) {
  modal.outerHTML = "<%= j render partial: "form", locals: { instructor: @instructor } %>"
}

app/views/instructors/show.html.erb
<% @page_title = "#{@instructor.full_name}" %>

<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Dashboard</a></li>
    <li class="breadcrumb-item"><a href="<%= instructors_path %>">Instructors</a></li>
    <li class="breadcrumb-item active"><%= @page_title %></li>
  </ol>
  <div class="row">
    <div class="col-12">
      <br>
      <h5>Cohorts</h5>
      <% if @instructor.cohorts.any? %>
        <% @instructor.cohorts.each do |cohort| %>
        <li><%= link_to("#{cohort.name}", course_cohort_path(cohort.course, cohort)) %> (<%= cohort.start_date.strftime("%b %d, %Y") %> - <%= cohort.end_date.strftime("%b %d, %Y") %>) </li>
        <% end %>
      <% else %>
        <li>No cohorts assigned</li>
      <% end %>
    </div>
  </div>
</div>

app/views/instructors/update.js.erb
// manually toggle modal
$("#editInstructorModal").modal('toggle');
// re-render edited element
row = document.getElementById("instructor_<%= @instructor.id %>");
row.outerHTML = "<%= j render partial: "instructor", locals: { instructor: @instructor } %>";
// display flash messages
$("#flash_messages").html("<%= j (render partial: 'shared/flash' , locals: { flash: flash }).html_safe %>");
// turn form partial back into span
$("#edit_instructor_<%= @instructor.id %>").replaceWith("<span id='edit-form'></span>");
// scroll to top
$(document).ready(function () { $('html, body').animate({scrollTop:0}, 100); });