config/routes.rb
Rails.application.routes.draw do

  # root route if signed in
  authenticated do
    root 'welcome#index', as: :authenticated_root
  end

  # default root route
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  # rename paths
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  resources :courses do
    resources :cohorts
  end

  resources :instructors do
    resources :users
  end

  resources :admins do
    resources :users
  end

  resources :students

  resources :grades

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @course_count = Course.count
    @cohort_count = Cohort.count
    @student_count = Student.count
    @instructor_count = Instructor.count
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container-fluid">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active"><a href="<%= root_path %>">Dashboard</a></li>
  </ol>
  <!-- Icon Cards-->
  <div id="welcome-cards" class="row justify-content-md-center">

    <div class="col-md-5 mb-3 m-1">
      <div class="card text-white bg-danger o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-university"></i>
          </div>
          <div class="mr-5">Courses: <%= @course_count %></div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="<%= courses_path %>">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>

    <div class="col-md-5 mb-3 m-1">
      <div class="card text-white bg-warning o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-list"></i>
          </div>
          <div class="mr-5">Cohorts: <%= @cohort_count %></div>
        </div>
      </div>
    </div>

    <div class="col-md-5 mb-3 m-1">
      <div class="card text-white bg-success o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-users"></i>
          </div>
          <div class="mr-5">Students: <%= @student_count %></div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="<%= students_path %>">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>

    <div class="col-md-5 mb-3 m-1">
      <div class="card text-white bg-primary o-hidden h-100">
        <div class="card-body">
          <div class="card-body-icon">
            <i class="fa fa-fw fa-user-circle"></i>
          </div>
          <div class="mr-5">Instructors: <%= @instructor_count %></div>
        </div>
        <a class="card-footer text-white clearfix small z-1" href="<%= instructors_path %>">
          <span class="float-left">View Details</span>
          <span class="float-right">
            <i class="fa fa-angle-right"></i>
          </span>
        </a>
      </div>
    </div>

  </div>

  <% if user_signed_in? && current_user.userable_type == "Admin" %>
    <div class="row justify-content-sm-center text-center">
      <div class="col-12 mt-5 mb-2">
        <h4>Quick Links</h4>
      </div>
      <div class="col-12 mb-4 text-center">
        <a href="<%= new_course_path %>" class="btn btn-outline-danger m-1 quick-links-btn" role="button">Add Course</a>
        <a href="<%= new_student_path %>" class="btn btn-outline-success m-1 quick-links-btn" role="button">Add Student</a>
        <a href="<%= new_instructor_path %>" class="btn btn-outline-primary m-1 quick-links-btn" role="button">Add Instructor</a>
        <a href="<%= new_admin_path %>" class="btn btn-outline-secondary m-1 quick-links-btn" role="button">Add Admin</a>
      </div>
    </div>
  <% end %>

</div>